sudo: false
language: java

env:
  global:
    - GRADLE_OPTS=-Xmx512m

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk: openjdk8

script:
  - ./gradlew check --stacktrace
after_success:
  - ./travis.sh deploy
  - ./travis.sh sonarqube

